# Production Configuration
spring.application.name=HRM
server.port=8080

# Disable SQL logging in production
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# Production Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hrm
spring.datasource.username=root
spring.datasource.password=Ijse@123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=6YS6/n7egeA1Ezi5PpPWKTE7HQ9/4DKbfAKXjiJ1U6M=
jwt.expiration=86400000
spring.main.allow-circular-references=true

# SMTP server configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=knowebtest@gmail.com
spring.mail.password=riem jmmz cyzh fqml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Stripe Configuration
stripe.api.key=sk_test_51Q5Sl8LS4Zd4e05LgSQbR0smc5P8b9y6Gr6umDayeHDDhRk9nWVjCXgK6gaiWXk98N50F5Kv8HOPd9WKaxsUZdyB00vPmMeKbz
stripe.webhook.secret=whsec_SKZ1Usco60NMBustPeINsLWFrFP3ESxF

# Production Domain
app.domain=http://129.212.239.12

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# CORS Configuration for production
cors.allowed-origins=http://129.212.239.12

# Production profile
spring.profiles.active=production
